version: '3'
services:
  app:
    build: .
    volumes:
      - .:/code
      - ./logs/supervisor:/var/log/supervisor
    networks:
      - web_nw
    expose:
      - 8000

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./settings/nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
      - web_nw
    depends_on:
      - app

networks:
  web_nw:
    driver: bridge
